---
name: autofix.ci
on: pull_request
permissions: {}
jobs:
  autofix:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 15
    steps:
      - uses: suzuki-shunsuke/go-autofix-action@feat-takumi-guard
        with:
          aqua_version: v2.59.1
          takumi_guard_bot_id: ${{secrets.TAKUMI_GUARD_BOT_ID}}
